---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{id}/feeds":
    get:
      summary: Get all feeds
      tags:
      - Feeds
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of feeds per page
        schema:
          type: integer
      responses:
        '200':
          description: returns all feeds
        '404':
          description: user not found
  "/api/v1/users/{id}/followings":
    post:
      summary: Follow a user
      tags:
      - Followings
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: following created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11111
                  follower_id:
                    type: integer
                    example: 22222
                  followed_id:
                    type: integer
                    example: 33333
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - follower_id
                - followed_id
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                followed_id:
                  type: integer
              required:
              - followed_id
  "/api/v1/users/{id}/followings/{following_id}":
    delete:
      summary: Unfollow a user
      tags:
      - Followings
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      - name: following_id
        in: path
        description: Following ID
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: following deleted
        '404':
          description: user or following not found
  "/api/v1/users/{id}/sleep_records":
    post:
      summary: Clock in a sleep record
      tags:
      - Sleep Records
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: sleep record created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11111
                  user_id:
                    type: integer
                    example: 22222
                  slept_at:
                    type: string
                    format: date-time
                  woke_at:
                    type: string
                    format: date-time
                    nullable: true
                    example: 
                  duration_minutes:
                    type:
                    - integer
                    - 'null'
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - user_id
                - slept_at
        '404':
          description: user not found
  "/api/v1/users/{id}/sleep_records/{sleep_record_id}":
    put:
      summary: Clock out a sleep record
      tags:
      - Sleep Records
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      - name: sleep_record_id
        in: path
        description: Sleep Record ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: sleep record updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11111
                  user_id:
                    type: integer
                    example: 22222
                  slept_at:
                    type: string
                    format: date-time
                  woke_at:
                    type: string
                    format: date-time
                    nullable: true
                  duration_minutes:
                    type: integer
                    example: 60
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - user_id
                - woke_at
        '404':
          description: user or sleep record not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
